version: '3'

services:
     web:
       image: nginx:alpine
       container_name: nginx
       restart: always
       ports:
           - "80:80"
           - "443:443"
       volumes:
           - ./src:/var/www/html
           - ./conf.d:/etc/nginx/conf.d
           - /etc/localtime:/etc/localtime
           - ./dhparam:/etc/nginx/dhparam
           - ./certbot/conf/:/etc/nginx/ssl/
           - ./certbot/data:/usr/share/nginx/html/letsencrypt    
       depends_on:
           - certbot
       networks:
           - nginxphp

     php:
       container_name: php 
       build:
          context: .
          dockerfile: php.dockerfile
       volumes:
           - ./src:/var/www/html
       expose:
           - 9000
       networks:
           - nginxphp
     certbot:
       container_name: certbot         
       image: certbot/certbot:latest
       command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email admin@cinamon.digital --agree-tos --no-eff-email -d *.chi.coffee
       volumes:
          - ./certbot/conf/:/etc/letsencrypt
          - ./certbot/logs/:/var/log/letsencrypt
          - ./certbot/data:/usr/share/nginx/html/letsencrypt      
       
networks:
     nginxphp: